// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJq7_X0Hv5NcZs4WTSziyeHBRstfqgcE',
    appId: '1:959302947978:web:abdd698b6ab8a0e87d4973',
    messagingSenderId: '959302947978',
    projectId: 'loyalty-8e0e5',
    authDomain: 'loyalty-8e0e5.firebaseapp.com',
    storageBucket: 'loyalty-8e0e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNGjEZRBZwefCTr-W1BR82V4kCSQGY_sM',
    appId: '1:959302947978:android:d9db6aad9ff220097d4973',
    messagingSenderId: '959302947978',
    projectId: 'loyalty-8e0e5',
    storageBucket: 'loyalty-8e0e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUtys0GGnMKiOyPovVCiVsJh0M4hILEo',
    appId: '1:959302947978:ios:c0cf48f5d11b446f7d4973',
    messagingSenderId: '959302947978',
    projectId: 'loyalty-8e0e5',
    storageBucket: 'loyalty-8e0e5.appspot.com',
    iosBundleId: 'com.kamm.loyalty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAUtys0GGnMKiOyPovVCiVsJh0M4hILEo',
    appId: '1:959302947978:ios:c61c3dc1e71662427d4973',
    messagingSenderId: '959302947978',
    projectId: 'loyalty-8e0e5',
    storageBucket: 'loyalty-8e0e5.appspot.com',
    iosBundleId: 'com.kamm.loyalty.RunnerTests',
  );
}
