// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB7e-tXtKcdz6HGu-oHPOwINcggkXbrBw',
    appId: '1:642297853297:web:e5be53e67b4cc71b9d72d0',
    messagingSenderId: '642297853297',
    projectId: 'loyalty-c0110',
    authDomain: 'loyalty-c0110.firebaseapp.com',
    storageBucket: 'loyalty-c0110.appspot.com',
    measurementId: 'G-PWBGFF5YK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4fMfM1ab_tyMwzTaz7X-pxoBrPylI9AM',
    appId: '1:642297853297:android:901fa63cc6c7c94f9d72d0',
    messagingSenderId: '642297853297',
    projectId: 'loyalty-c0110',
    storageBucket: 'loyalty-c0110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6kSuwFD8pgdnMbebYk0kMwAjFx0fMx4',
    appId: '1:642297853297:ios:04e558d6222c062c9d72d0',
    messagingSenderId: '642297853297',
    projectId: 'loyalty-c0110',
    storageBucket: 'loyalty-c0110.appspot.com',
    iosBundleId: 'com.beringin.loyatly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6kSuwFD8pgdnMbebYk0kMwAjFx0fMx4',
    appId: '1:642297853297:ios:f5d9716c20122d0b9d72d0',
    messagingSenderId: '642297853297',
    projectId: 'loyalty-c0110',
    storageBucket: 'loyalty-c0110.appspot.com',
    iosBundleId: 'com.kamm.loyalty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB7e-tXtKcdz6HGu-oHPOwINcggkXbrBw',
    appId: '1:642297853297:web:0d4b6fdcd95c74dc9d72d0',
    messagingSenderId: '642297853297',
    projectId: 'loyalty-c0110',
    authDomain: 'loyalty-c0110.firebaseapp.com',
    storageBucket: 'loyalty-c0110.appspot.com',
    measurementId: 'G-J07FB2RSPL',
  );

}